import type { Metadata } from "next";
import "./globals.css";
import { TanStackQueryProvider } from "@/lib/tan-stack-query-provider";
import { Noto_Sans } from "next/font/google";

const notoSans = Noto_Sans({ variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" className={notoSans.variable}>
      <body>
        <TanStackQueryProvider>{children}</TanStackQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
