import type { Metadata } from "next";
import "./globals.css";
import { TanStackQueryProvider } from "@/lib/TanStackQueryProvider";
import { Saira } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const saira = Saira({ subsets: ["latin"] });

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={saira.className}>
        <TanStackQueryProvider>{children}</TanStackQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
